### ISSUE TITLE
Onboarding todo

### ISSUE THREAD

**Issue by antonve** [antonve/langlog-ios#12]
## Business logic

- [ ] Create `AppState`
- [ ] Create `AuthRepository`
  - [ ] Implement login logic
  - [ ] Implement sign up logic
- [ ] Create `UserAccountUseCase`
  - [ ] Implement login logic
  - [ ] Implement sign up logic
  - [ ] Implement log out
  - [ ] Refresh token

## Welcome screen
- [x] Start welcome coordinator on launch
- [ ] Launch app when login has been completed
- [x] Show log in button
  - [x] Tap: show log in screen
- [x] Show sign up button
  - [x] Tap: show sign up screen

## Log in screen

- [x] Create UI https://github.com/antonve/langlog-ios/pull/11
- [ ] Show errors in UI
- [ ] Reactor
  - [ ] Login handling
  - [ ] Validation/feedback

## Sign up screen

- [x] Create UI https://github.com/antonve/langlog-ios/pull/10
- [ ] Show errors in UI
- [ ] Reactor
  - [ ] Sign up handling
  - [ ] Validation/feedback
